# Generated by Django 3.0.5 on 2020-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200423_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=None, verbose_name='published date'),
            preserve_default=False,
        ),
    ]
